accessing
languages
	"#(az be bg cs de en es fr hy it lt mk pl pt ro ru tr uk)"

	^ OrderedCollection new
		add: {'Azerbaijani' . #az};
		add: {'Belarusian' . #be};
		add: {'Bulgarian' . #bg};
		add: {'Czech' . #cs};
		add: {'Deutschland' . #de};
		add: {'English' . #en};
		add: {'Spanish' . #es};
		add: {'French' . #fr};
		add: {'Armenian' . #hy};
		add: {'Italian' . #it};
		add: {'Lithuanian' . #lt};
		add: {'Macedonian' . #mk};
		add: {'Polish' . #pl};
		add: {'Portuguese' . #pt};
		add: {'Ro' . #ro};
		add: {'Russian' . #ru};
		add: {'Turkish' . #tr};
		add: {'Ukranian' . #uk}; yourself